### ISSUE TITLE
Auto Focus Request in JFX does not work

### ISSUE THREAD

**Issue by tlf30** [jayfella/jme-jfx-11#1]
In a JFX UI, requesting focus does not cause JME to give it focus.

**Comment by James-Khan** [comment]
Methods have been added to solve this issue.

https://github.com/jayfella/jme-jfx-11/blob/master/src/main/java/com/jayfella/jme/jfx/JavaFxUI.java#L104

**Comment by tlf30** [comment]
Thank you, I will test when I get home next week.

**Comment by James-Khan** [comment]
See this thread for more information. 

https://hub.jmonkeyengine.org/t/javafx-jmefxinputlistener-consuming-button-release-events/42482/13?u=jayfella

**Comment by tlf30** [comment]
Hello @jayfella, do you have snapshots setup in any repo, or do I need to build from source?
If not, it would be really nice to have snapshots.

**Comment by jayfella** [comment]
I do not have snapshots, however I believe you can use jitpack to pull straight from the master branch.

**Comment by tlf30** [comment]
It looks like the request/loose focus is working great. Thank you!
When do you think this will be ready for the next release?

**Comment by jayfella** [comment]
Now. Version 1.1.5 on jcenter.
