### ISSUE TITLE
Question - does this allow JME to be embedded inside a JavaFx container (say like a BorderPane)?

### ISSUE THREAD

**Issue by dsobiera** [jayfella/jme-jfx-11#10]
My apologies if this isn't the correct place for a question (not really an issue). If this is the wrong place, please let me know where I can ask.

I went over the README and got a simple button to appear on-top of my JME game window. YAY!!!

What I am wondering is if this will allow me to say put the JME display inside say the "CENTER" of a JavaFX BorderPane?

If so, any examples on how one would do that?

**Comment by jayfella** [comment]
This library embeds jfx into JME. I also made a library that embeds JME into jfx. 

https://github.com/jayfella/jfx-11-jme-embedded

Note though that performance is not that great. It’s primarily for business applications, not game development. The frame rate of the game does suffer.
