### ISSUE TITLE
When moving the mouse pointer the log generates ->  java.lang.NoSuchMethodError: com.sun.javafx.embed.EmbeddedSceneInterface.mouseEvent(int, int, boolean, boolean, boolean, int, int, int, int, boolean, boolean, boolean, boolean, boolean)' 

### ISSUE THREAD

**Issue by dsobiera** [jayfella/jme-jfx-11#9]
I am just generating a simple button for a test in a jme3 app. The Button seems to render but when I move the mouse anywhere on the JME window the log fills w/ lots of:

Exception in thread "JavaFX Application Thread" java.lang.NoSuchMethodError: 'void com.sun.javafx.embed.EmbeddedSceneInterface.mouseEvent(int, int, boolean, boolean, boolean, int, int, int, int, boolean, boolean, boolean, boolean, boolean)'

Am I missing a dependency?

I am running jdk 11.0.8+10 on 64 bit Ubuntu.

**Comment by jayfella** [comment]
What version of javafx are you pulling in the javafx options? It must be 11.

**Comment by dsobiera** [comment]
Yup...that was it.  

I was at 14.0.2.1.  When i put it at 11.0.1 all works fine.

Sorry about that and thanks!

**Comment by jayfella** [comment]
No worries :)
